#!/usr/bin/env bash
set -euo pipefail

# Resolve this script's directory (must be run from within dwm repo)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$SCRIPT_DIR"
PREFIX="${PREFIX:-$HOME/.local}"

# 1. Check if this is a git repo
if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "ERROR: This is not a Git repository: $REPO_DIR"
  exit 1
fi

cd "$REPO_DIR"

# 2. Sync with upstream
echo "Fetching upstream…"
git fetch upstream

CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
echo "Merging upstream/master into $CURRENT_BRANCH…"
git merge --no-edit upstream/master

# 3. Build
echo "Building dwm…"
make clean
make

# 4. Install
echo "Installing to $PREFIX…"
make install PREFIX="$PREFIX"

# 5. Create default xinitrc if needed
if [[ ! -f "$HOME/.xinitrc" ]]; then
  cat > "$HOME/.xinitrc" <<EOF
# ~/.xinitrc autogenerated by dwm-update.sh
exec dwm
EOF
  echo "Created ~/.xinitrc template"
fi

echo "✔ DWM update complete."

