#!/usr/bin/env bash
set -euo pipefail

# Configuration: adjust these if your paths differ
REPO_DIR="$HOME/dev/dwm"
PREFIX="${PREFIX:-$HOME/.local}"

# 1. Ensure repo exists
if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "ERROR: Repo not found at $REPO_DIR"
  exit 1
fi

cd "$REPO_DIR"

# 2. Sync with upstream
#    (expects `upstream` remote pointing at https://git.suckless.org/dwm)
echo "Fetching upstream…"
git fetch upstream

# Merge upstream/master into your current branch
CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
echo "Merging upstream/master into $CURRENT_BRANCH…"
git merge --no-edit upstream/master

# 3. Build
echo "Building dwm…"
make clean
make

# 4. Install
echo "Installing to $PREFIX…"
make install PREFIX="$PREFIX"

# 5. (Optional) Copy a template .xinitrc if none exists
if [[ ! -f "$HOME/.xinitrc" ]]; then
  cat > "$HOME/.xinitrc" <<EOF
# ~/.xinitrc autogenerated by dwm-update.sh

# Start any background programs here
# e.g. nm-applet &

exec dwm
EOF
  echo "Created ~/.xinitrc template"
fi

echo "Done! If you’re in X already, log out and select the dwm session, or run startx."

